include_recipe 'java'
include_recipe 'monit'
include_recipe 'elasticsearch'
include_recipe 'elasticsearch::monit'
include_recipe 'elasticsearch::search_discovery'
include_recipe 'elasticsearch::aws'
include_recipe 'optoro_metrics::elasticsearch'
